#ifndef FIR_H
#define FIR_H

#include <stdint.h>

/*
  Decimating FIR low-pass, the antialias filter the wave chain decimates through.

  Replaces a boxcar mean. A mean over D samples IS an FIR filter, but a poor one:
  |sin(pi f D/fs) / (D sin(pi f/fs))| has nulls at multiples of the output rate and
  leaks heavily between them, so everything above Nyquist folds down into the wave
  band. A windowed-sinc filter attenuates what has to go.

  Deliberately free of Arduino, LSM6DSV16X and wave_config.h dependencies (same rule
  as madgwick.h / rotation.h), so it compiles on a host and its impulse response can
  be checked against tools/fir.py without flashing anything. The
  coefficients are supplied by the caller - one class covers both decimation stages.

  push/eval are separate on purpose, and that separation is the whole point of a
  DECIMATING FIR: the input side is a plain store, run at the input rate, while the
  convolution is only evaluated at the far rarer output samples. At a decimation of
  D that is 65 multiplies per OUTPUT sample rather than per input sample - the
  difference between affordable and not on a soft-float 48 MHz core, and the reason
  lowering the row rate barely helps while lowering the ODR does. Do not merge them
  into a single filter() call.
*/

static constexpr uint16_t kFirNtap = 129;              // matches fir.py's NTAP
static constexpr uint16_t kFirHalf = (kFirNtap - 1) / 2;  // group delay, in samples

static_assert(kFirNtap % 2 == 1,
              "odd tap count - a linear-phase group delay of (N-1)/2 must be a whole "
              "number of samples, otherwise it cannot be compensated by indexing");

class FirDecimator {
 public:
  // coeffs must outlive the filter and hold kFirNtap symmetric taps (see
  // fir_coeffs.h, generated by tools/gen_fir_table.py).
  explicit FirDecimator(const float *coeffs) : c_(coeffs) {}

  // Zero the delay line. The first kFirNtap outputs after this are contaminated by
  // the zero fill - the capture warm-up covers that (see kFirNtap assert in
  // wave_config.h).
  void reset(void);

  // One INPUT sample: a store and an index bump, nothing else.
  void push(float x);

  // One OUTPUT sample: 65 multiplies + 128 adds, symmetry-folded. Const - reading
  // the filter does not advance it, so a caller may evaluate the same state twice
  // (the late-eval path in ImuSampler relies on that being harmless).
  float eval(void) const;

  // The UNFILTERED input sample that eval() is centred on, i.e. the one kFirHalf
  // pushes back. Free: the delay line already holds it. Logging it next to eval()
  // gives a filtered/unfiltered pair on one time base, which is what makes the
  // vacc vs vacc_fir comparison in the capture logs meaningful rather than
  // a comparison of two different instants.
  float center(void) const { return z_[(uint16_t)((idx_ + kFirHalf) % kFirNtap)]; }

 private:
  const float *c_;
  float    z_[kFirNtap] = {0};
  uint16_t idx_ = 0;   // next write slot; the newest sample sits at idx_-1
};

#endif  // FIR_H
