#ifndef FIR_H
#define FIR_H

#include <stdint.h>

/*
  Decimating FIR low-pass, the antialias filter the wave chain decimates through.
*/

static constexpr uint16_t kFirNtap = 31;   // Need to run gen_fir_table.py to change this value
static constexpr uint16_t kFirHalf = (kFirNtap - 1) / 2;  // group delay, in samples

static_assert(kFirNtap % 2 == 1,
              "odd tap count - a linear-phase group delay of (N-1)/2 must be a whole "
              "number of samples, otherwise it cannot be compensated by indexing");

class FirDecimator {
 public:
  // coeffs must outlive the filter and hold kFirNtap symmetric taps (see
  // fir_coeffs.h, generated by tools/gen_fir_table.py).
  explicit FirDecimator(const float *coeffs) : c_(coeffs) {}

  // Zero the delay line. The first kFirNtap outputs after this are contaminated by
  // the zero fill - the capture warm-up covers that (see kFirNtap assert in
  // wave_config.h).
  void reset(void);

  // Store one input sample into the FIR - line.
  void push(float x);

  // Get one output sample. Does not advance the delay line, so can be called multiple
  // times after a single push() to get the same output sample
  float eval(void) const;

  // The unfiltered input sample that eval() is centred on, i.e. the one kFirHalf
  // pushes back. 
  float center(void) const { return z_[(uint16_t)((idx_ + kFirHalf) % kFirNtap)]; }

 private:
  const float *c_;
  float    z_[kFirNtap] = {0};
  uint16_t idx_ = 0;   // next write slot; the newest sample sits at idx_-1
};

#endif  // FIR_H
