#!/usr/bin/env python3
"""Generate welch_window.h for the firmware - the Welch window weights as a constexpr array.

The weights depend only on kWelchSegLen and kWelchWindow, both constexpr in
wave_config.h, so they are the same for every capture.
The firmware cannot compute them itself in constexpr, and pre-computing them
saves one sinf per sample in the loop where IMU FIFO is read.

Usage:
  python gen_welch_window.py \\
      -o ../firmware/common_libraries/wave_manager/src/welch_window.h

If kWelchSegLen or kWelchWindow changes in wave_config.h, this has to be run again. The
firmware's static_assert stops the build and says which of the two no longer matches.
"""

import argparse
import sys
import numpy as np

# Must follow enum class WindowType { Hann, Hamming } in wave_config.h
WINDOW_KIND = {"hann": "WindowType::Hann", "hamming": "WindowType::Hamming"}

# kWelchSegLen in wave_config.h. Mirrored here rather than read out of the header
DEFAULT_SEGLEN = 1024

# Window type in wave_config.h. Mirrored here rather than read out of the header
DEFAULT_WINDOW = "hann"


def window_weights(n, kind):
    """Window weights w[0..n-1] (i/N indexing, as in the firmware)."""
    i = np.arange(n, dtype=np.float64)
    if kind == "hamming":
        return 0.54 - 0.46 * np.cos(2.0 * np.pi * i / n)
    s = np.sin(np.pi * i / n)          # Hann = sin²(πi/N)
    return s * s

def lit(v):
    """One float32 repr, with the decimal point forced in, because 0f is not a valid C++ literal."""
    s = f"{np.float32(v):.9g}"
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s + "f"


def fmt_table(name, weights, per_line=4):
    out = [f"inline constexpr float {name}[{len(weights)}] = {{"]
    for i in range(0, len(weights), per_line):
        chunk = weights[i:i + per_line]
        out.append("    " + " ".join(lit(v) + "," for v in chunk))
    out.append("};")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seglen", type=int, default=DEFAULT_SEGLEN,
                    help=f"kWelchSegLen (default {DEFAULT_SEGLEN})")
    ap.add_argument("--window", choices=sorted(WINDOW_KIND), default=DEFAULT_WINDOW,
                    help=f"kWelchWindow (default {DEFAULT_WINDOW})")
    ap.add_argument("-o", "--out", default="-", help="output file, '-' for stdout")
    args = ap.parse_args()

    n = args.seglen
    if n < 2 or (n & (n - 1)) != 0:
        sys.exit(f"seglen {n} is not a power of two")

    w = window_weights(n, args.window)

    # Reasonability check, window should be in [0,1].
    if w.min() < -1e-12 or w.max() > 1.0 + 1e-12:
        sys.exit(f"window weights outside [0,1]: {w.min()!r}..{w.max()!r}")

    # The window is symmetric about N/2, so w[i] == w[N-i] for i=1..N-1
    if not np.allclose(w[1:], w[1:][::-1], atol=1e-12):
        sys.exit("the window weights are not symmetric about N/2")

    # sum(w^2) is the normalisation accumSegment divides by, so it is what the float32
    # rounding could have shifted the level with. The firmware sums the float32 weights
    # in double, so it is that sum that has to hold - not the float64 weights'.
    s2_f64 = float(np.sum(w * w))
    s2_f32 = float(np.sum(np.float32(w).astype(np.float64) ** 2))
    if abs(s2_f32 - s2_f64) > 1e-6 * s2_f64:
        sys.exit(f"sum(w^2) moved too far in float32: {s2_f64!r} -> {s2_f32!r}")

    kind = WINDOW_KIND[args.window]
    body = f"""#ifndef WELCH_WINDOW_H

#define WELCH_WINDOW_H

#include "wave_config.h"   // kWelchSegLen, kWelchWindow

/*
  GENERATED by tools/gen_welch_window.py - do not edit by hand.

  The Welch segment window weights.

  The weights depend only on kWelchSegLen and kWelchWindow, both constexpr.
  Computing them per segment cost {n} sinf calls, and with no FPU that was around 
  30 of the 117 ms the whole FFT took inside the capture loop.

  The whole window, not half for simplicity. Hann and Hamming are both symmetric about N/2, so {n // 2 + 1}
  values would do - but every lookup in the loop would then need to check
  i <= N/2 ? t[i] : t[N-i]. The table is in flash, not RAM, so the extra 2 kB is an ok trade-off.

  These weights are computed in float64 and rounded to float32 once.

  The sum of the squared weights is computed in firmware to avoid any rounding errors.
*/

// The length and window type are baked into the values
// If they are changed, then the firmware's static_assert will stop the build and say which one no longer matches.
inline constexpr uint16_t kWelchWindowTableLen  = {n};
inline constexpr WindowType  kWelchWindowTableKind = {kind};   // WindowType::{args.window.capitalize()}

static_assert(kWelchWindowTableLen == kWelchSegLen,
              "kWelchSegLen changed - regenerate welch_window.h with "
              "tools/gen_welch_window.py --seglen <n>");
static_assert(kWelchWindowTableKind == kWelchWindow,
              "kWelchWindow changed - regenerate welch_window.h with "
              "tools/gen_welch_window.py --window <hann|hamming>");

{fmt_table("kWelchWindowTable", w)}

#endif  // WELCH_WINDOW_H
"""

    if args.out == "-":
        sys.stdout.write(body)
    else:
        with open(args.out, "w") as f:
            f.write(body)
        print(f"wrote {args.out}: {n} weights, window {args.window}, "
              f"sum(w^2) = {s2_f32:.9g}")


if __name__ == "__main__":
    main()
