#!/usr/bin/env python3
"""Generate welch_window.h for the firmware - the Welch window weights as a constexpr array.

The weights depend only on kWelchSegLen and kWelchWindow, both constexpr in
wave_config.h, so they are the same for every single segment of every single capture.
The firmware cannot compute them itself (no sin/cos in constexpr), and computing them
per segment costs one sinf per sample - the most expensive single operation in the FFT
on an M4 without an FPU, inside the longest stretch where the FIFO is not read. As
constexpr the table lands in .rodata (flash) and costs no RAM at all.

The table is generated from welch.window_weights, which IS the function the offline
chain uses, so the device and the offline chain cannot drift apart.

Usage:
  python gen_welch_window.py \\
      -o ../firmware/common_libraries/wave_manager/src/welch_window.h

If kWelchSegLen or kWelchWindow changes in wave_config.h, this has to be run again. The
firmware's static_assert stops the build and says which of the two no longer matches.
"""

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import welch  # noqa: E402

# Must follow enum class WindowType { Hann, Hamming } in wave_config.h: the keys are the
# strings welch.window_weights understands, the values the enum's numeric values.
WINDOW_KIND = {"hann": 0, "hamming": 1}

# kWelchSegLen in wave_config.h. Mirrored here rather than read out of the header: a
# parser for C++ would be one more thing that could fail quietly, and the static_assert
# on the other side catches a mismatch at build time anyway.
DEFAULT_SEGLEN = 1024
DEFAULT_WINDOW = "hann"


def lit(v):
    """One float32 repr, with the decimal point forced in. The Hann window starts at
    exactly 0, and %.9g then gives "0", which with the suffix becomes "0f" - not a float
    literal at all, but an integer followed by an identifier."""
    s = f"{np.float32(v):.9g}"
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s + "f"


def fmt_table(name, weights, per_line=4):
    out = [f"inline constexpr float {name}[{len(weights)}] = {{"]
    for i in range(0, len(weights), per_line):
        chunk = weights[i:i + per_line]
        out.append("    " + " ".join(lit(v) + "," for v in chunk))
    out.append("};")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seglen", type=int, default=DEFAULT_SEGLEN,
                    help=f"kWelchSegLen (default {DEFAULT_SEGLEN})")
    ap.add_argument("--window", choices=sorted(WINDOW_KIND), default=DEFAULT_WINDOW,
                    help=f"kWelchWindow (default {DEFAULT_WINDOW})")
    ap.add_argument("-o", "--out", default="-", help="output file, '-' for stdout")
    args = ap.parse_args()

    n = args.seglen
    if n < 2 or (n & (n - 1)) != 0:
        sys.exit(f"seglen {n} is not a power of two - the FFT is radix-2")

    w = welch.window_weights(n, args.window)

    # The fence against a table that looks reasonable but is the wrong window: both
    # windows are symmetric about N/2 and lie in [0,1].
    if w.min() < -1e-12 or w.max() > 1.0 + 1e-12:
        sys.exit(f"window weights outside [0,1]: {w.min()!r}..{w.max()!r}")
    if not np.allclose(w[1:], w[1:][::-1], atol=1e-12):
        sys.exit("the window weights are not symmetric about N/2 - wrong formula")

    # sum(w^2) is the normalisation accumSegment divides by, so it is what the float32
    # rounding could have shifted the level with. The firmware sums the float32 weights
    # in double, so it is that sum that has to hold - not the float64 weights'.
    s2_f64 = float(np.sum(w * w))
    s2_f32 = float(np.sum(np.float32(w).astype(np.float64) ** 2))
    if abs(s2_f32 - s2_f64) > 1e-6 * s2_f64:
        sys.exit(f"sum(w^2) moved too far in float32: {s2_f64!r} -> {s2_f32!r}")

    kind = WINDOW_KIND[args.window]
    body = f"""#ifndef WELCH_WINDOW_H
#define WELCH_WINDOW_H

#include "wave_config.h"   // kWelchSegLen, kWelchWindow - the fence below checks both

/*
  GENERATED by tools/gen_welch_window.py - do not edit by hand.

  The Welch segment window weights, from the same function postprocess.py uses offline:
  welch.window_weights. That is the whole reason they are generated rather than written
  in two places - with one formula, the device and offline weights cannot drift apart.

  WHY A TABLE. The weights depend only on kWelchSegLen and kWelchWindow, both constexpr,
  so they are identical for every segment of every capture. Computing them per segment
  cost {n} sinf calls, and with no FPU that was ~30 of the 117 ms the whole FFT took -
  inside the longest stretch of the capture loop where the FIFO is not read.

  THE WHOLE WINDOW, NOT HALF. Hann and Hamming are both symmetric about N/2, so {n // 2 + 1}
  values would do - but every lookup in the hot loop would then need
  i <= N/2 ? t[i] : t[N-i], and the symmetry would be one more thing that could be
  wrong. The table is in .rodata (flash, ~52 % used), not RAM (~84 % used), so
  {n * 4} B against {(n // 2 + 1) * 4} B is no trade-off at all.

  NOT BIT-IDENTICAL to sinf. These are computed in float64 and rounded to float32 once;
  newlib's sinf works in float32 throughout and can differ by 1 ULP. psdAcc_ therefore
  matches to ~1e-7 relative, not bit for bit - physically irrelevant, since hs and tz
  are integrals over {n // 2 + 1} bins, and the table is closer to the reference than the
  code was.

  The sum(w^2) normalisation is DELIBERATELY not generated here. accumSegment sums the
  table itself (ensureS2), so it cannot fall out of step with the weights it normalises
  - one less place where Python and C could compute slightly different things.
*/

// The length and window type are baked into the values. Changing either without
// regenerating makes the spectrum quietly wrong - hence a fence, not a comment.
inline constexpr uint16_t kWelchWindowTableLen  = {n};
inline constexpr uint8_t  kWelchWindowTableKind = {kind};   // WindowType::{args.window.capitalize()}

static_assert(kWelchWindowTableLen == kWelchSegLen,
              "kWelchSegLen changed - regenerate welch_window.h with "
              "tools/gen_welch_window.py --seglen <n>");
static_assert(kWelchWindowTableKind == (uint8_t)kWelchWindow,
              "kWelchWindow changed - regenerate welch_window.h with "
              "tools/gen_welch_window.py --window <hann|hamming>");

{fmt_table("kWelchWindowTable", w)}

#endif  // WELCH_WINDOW_H
"""

    if args.out == "-":
        sys.stdout.write(body)
    else:
        with open(args.out, "w") as f:
            f.write(body)
        print(f"wrote {args.out}: {n} weights, window {args.window}, "
              f"sum(w^2) = {s2_f32:.9g}")


if __name__ == "__main__":
    main()
